django_troop/django_troop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("scouts.urls")),
    path("admin/", admin.site.urls),
    path("imports/", include("imports.urls")),
    path("accounts/", include("allauth.urls")),
    path("scouts/", include("scouts.urls")),
    path("adults/", include("scouts.adult_urls")),
    path("users/", include("scouts.user_urls")),
    path("patrols/", include("patrols.urls")),
    path("positions/", include("positions.urls")),
    path("leaders/", include("leaders.urls")),
    path("badges/", include("badges.urls")),
    path("signoffs/", include("signoffs.urls")),
    path("site_admin/", include("site_admin.urls")),
    path("invitations/", include("invitations.urls", namespace="invitations")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns


# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

django_troop/setup/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.setup, name="setup"),
]

django_troop/signoffs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("update/", views.signoff_update, name="signoff_update"),
    path("delete/", views.signoff_delete, name="signoff_delete"),
]

django_troop/signoffs/models.py
from django.db import models
from requirements.models import Requirement


class UnsignedRequirementsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(signed=False)


class SignedRequirementsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(signed=True)


class RankBadgeFinalSignoffsManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(
                requirement__final_requirement__isnull=False,
                requirement__badge__badge_type="rank",
            )
        )


class Signoff(models.Model):
    date = models.DateField(default=None, null=True, blank=True)
    scout = models.ForeignKey("scouts.User", on_delete=models.CASCADE)
    signed = models.BooleanField(default=False, blank=True)
    requirement = models.ForeignKey(
        "requirements.Requirement", on_delete=models.CASCADE, related_name="signoffs"
    )

    objects = models.Manager()
    unsigned_requirements = UnsignedRequirementsManager()
    signed_requirements = SignedRequirementsManager()
    final_signoffs = RankBadgeFinalSignoffsManager()

    class Meta:
        unique_together = ["requirement", "scout"]
        permissions = [
            ("signoff_allowed", "Can sign off requirements"),
            ("signoff_proposer", "Can propose signoffs to be approved"),
            ("signoff_approver", "Can approve proposed signoffs"),
            ("merit_badge_signer", "Can sign off merit badge requirements"),
        ]

    def __str__(self):
        return f"<{self.__class__.__name__} {self.scout.last_name} {self.requirement.badge.name } {self.requirement.code} {self.signed}>"

    @classmethod
    def complete(cls, scout, badge):
        try:
            badge_completed = cls.final_signoffs.filter(
                requirement__badge=badge, scout=scout, signed=True
            ).exists()
        except cls.DoesNotExist:
            pass

        all_count = Requirement.objects.filter(badge=badge).count()

        signed_count = (
            cls.signed_requirements.filter(requirement__badge=badge)
            .filter(scout=scout)
            .count()
        )

        return badge_completed or all_count == signed_count

django_troop/signoffs/views.py
from datetime import date

from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
from django.template import loader
from icecream import ic
from signoffs.models import Signoff


@permission_required("signoffs.signoff_allowed")
def signoff_update(request):
    template = loader.get_template("signoffs/signed_off.html")
    signoff = Signoff.objects.get(pk=request.POST.get("code"))
    signoff.date = date.today()
    signoff.signed = True
    signoff.save()

    context = {"signoff": signoff}

    return HttpResponse(template.render(request=request, context=context))


@permission_required("signoffs.signoff_allowed")
def signoff_delete(request):
    template = loader.get_template("signoffs/not_signed_off.html")
    signoff = Signoff.objects.get(pk=request.POST.get("code"))
    signoff.date = None
    signoff.signed = False
    signoff.save()

    context = {"signoff": signoff}

    return HttpResponse(template.render(request=request, context=context))

django_troop/signoffs/templates/signoffs/not_signed_off.html
{% if perms.signoffs.change_signoff %}
<li hx-post="{% url 'signoff_update' %}" hx-swap="outerHTML" hx-vals='{"code": "{{signoff.pk}}" }' class="list-group-item">
{% else %}
<li class="list-group-item">
{% endif %}
	    {{ signoff.requirement.code }} {{ signoff.requirement.text }}</li>

django_troop/signoffs/templates/signoffs/signed_off.html
{% if perms.signoffs.change_signoff %}
<li hx-post="{% url 'signoff_delete' %}" hx-swap="outerHTML" hx-vals='{"code": "{{signoff.pk}}" }' class="list-group-item fw-lighter text-decoration-line-through">
{% else %}
<li class="list-group-item fw-lighter text-decoration-line-through">
{% endif %}
{{ signoff.requirement.code }} {{ signoff.requirement.text }} {{ signoff.date }}</li>

django_troop/signoffs/templates/signoffs/signoff_modal.html
<div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header">
	    <h5 class="modal-title">Signoff {{scout.first_name }} {{ scout.last_name}} for {{ signoff.requirement.badge.name }} {{ signoff.requirement.code }} {{ signoff.requirement.text }}</h5>
    </div>
    <div class="modal-body">
	    <p>{{ signoff.requirement.text }}</p>
	    {{ csrf_token }}
	    {{ form.as_p }}
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    </div>
  </div>
</div>