django_troop/django_troop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("scouts.urls")),
    path("admin/", admin.site.urls),
    path("imports/", include("imports.urls")),
    path("accounts/", include("allauth.urls")),
    path("scouts/", include("scouts.urls")),
    path("adults/", include("scouts.adult_urls")),
    path("users/", include("scouts.user_urls")),
    path("patrols/", include("patrols.urls")),
    path("positions/", include("positions.urls")),
    path("leaders/", include("leaders.urls")),
    path("badges/", include("badges.urls")),
    path("signoffs/", include("signoffs.urls")),
    path("site_admin/", include("site_admin.urls")),
    path("invitations/", include("invitations.urls", namespace="invitations")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns


# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

django_troop/positions/urls.py
from django.urls import path

from . import views
from .views import PositionDetailView, PositionListView

urlpatterns = [
    path("<int:pk>", PositionDetailView.as_view(), name="position_detail"),
    path("", PositionListView.as_view(), name="positions_list"),
    path("edit/<int:pk>/", views.position_edit, name="positions_update"),
    path("edit/new/", views.position_edit, name="positions_create"),
]

django_troop/setup/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.setup, name="setup"),
]

django_troop/leaders/models.py
from datetime import date

from django.db import models
from django.urls import reverse_lazy


class Leader(models.Model):
    start_date = models.DateField(default=date.today)
    end_date = models.DateField(null=True, blank=True)
    user = models.ForeignKey(
        "scouts.User", on_delete=models.CASCADE, related_name="leader_positions"
    )
    position = models.ForeignKey(
        "positions.Position", on_delete=models.CASCADE, related_name="leader_scouts"
    )

    comments = models.CharField(max_length=200, null=True, blank=True)
    mentor = models.ForeignKey(
        "scouts.User",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="mentor_positions",
    )

    def get_absolute_url(self):
        return reverse_lazy("leader_detail", kwargs={"pk": self.pk})

    def is_active(self):
        if self.end_date and self.end_date <= date.today():
            return False
        return True

    def __str__(self):
        return f"{self.user.first_name}, {self.user.last_name[0]} {self.position.name}"

django_troop/positions/models.py
from django.db import models


class Position(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200, null=True, blank=True)
    position_type = models.CharField(
        max_length=10,
        null=True,
        blank=True,
        choices=(("scout", "scout"), ("adult", "adult"), ("either", "either")),
    )

    def __str__(self):
        return f"{self.name}"

django_troop/positions/forms.py
from django import forms

from .models import Position


class PositionForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = "__all__"

django_troop/positions/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .forms import PositionForm
from .models import Position


class PositionListView(LoginRequiredMixin, ListView):
    model = Position
    context_object_name = "positions"
    template_name = "positions/positions_list.html"
    ordering = ["name"]


class PositionDetailView(LoginRequiredMixin, DetailView):
    model = Position
    context_object_name = "position"
    template_name = "positions/position_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["incumbents"] = (
            context["position"].leader_scouts.filter(end_date__isnull=True).all()
        )

        context["veterans"] = (
            context["position"].leader_scouts.filter(end_date__isnull=False).all()
        )

        return context


@permission_required("positions.change_position")
def position_edit(request, pk=None):
    if pk is not None:
        position = get_object_or_404(Position, pk=pk)
    else:
        position = None

    if request.method == "POST":
        form = PositionForm(request.POST, instance=position)
        if form.is_valid():
            updated_position = form.save()
            if position is None:
                messages.success(
                    request, 'Position "{}" was created.'.format(updated_position)
                )
            else:
                messages.success(
                    request, 'Position "{}" was updated.'.format(updated_position)
                )

            return redirect("position_edit", updated_position.pk)
    else:
        form = PositionForm(instance=position)

    return render(
        request, "positions/form-example.html", {"method": request.method, "form": form}
    )

django_troop/positions/templates/positions/form-example.html
{% extends 'base.html' %}

{% block title %}Positions{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <p><input type="submit" value="Submit"></p>
</form>
{% endblock %}

django_troop/positions/templates/positions/position_detail.html
{% extends 'base.html' %}

{% block title %}{{ position.name }}{% endblock %}

{% block content %}
    <table class="table">
	    <thead>
	    <tr>
            <th>Name</th>
            <th>Description</th>
	    </tr>
	    </thead>
	    <tbody>
        <tr>
		<td>{{ position.name }}</td>
		<td>{{ position.description }}</td>
{% if perms.leaders.add_leader %}
	        <td><a href="{% url 'leader_create_w_position' position.id %}"><button type="button" class="btn btn-primary">Assign New</button></a></td>
{% else %}
		<td></td>
{% endif %}
		<td></td>
        </tr>
	    </tbody>
    </table>

    <h3>Current Holders</h3>
    <table class="table table-striped table-hover">
	    <thead>
    <tr>
    <th>Name</th>
    <th>Start Date</th>
    <th></th>
    </tr>
	    </thead>
	    <tbody>

    {% for scout_ref in incumbents %}
    <tr>
	    <td>{{ scout_ref.user.first_name }} {{ scout_ref.user.last_name.0 }}</td>
	    <td>{{ scout_ref.start_date }} </td>
{% if perms.leaders.change_leader %}
            <td><a href="{% url 'leader_update' scout_ref.id %}"><button type="button" class="btn btn-primary">Update</button></a></td>
{% else %}
	    <td></td>
{% endif %}
    </tr>

    {% empty %}
    <tr>
	    <td>None</td>
	    <td>None</td>
    </tr>
    {% endfor %}

	    </tbody>
    </table>
	

    <h3>Previous Holders</h3>
    <table class="table table-striped table-hover">
	    <thead>
    <tr>
    <th>Name</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th></th>
    </tr>
	    </thead>
	    <tbody>

    {% for scout_ref in veterans %}
    <tr>
	    <td>{{ scout_ref.user.first_name }} {{ scout_ref.user.last_name.0 }}</td>
	    <td>{{ scout_ref.start_date }} </td>
	    <td>{{ scout_ref.end_date }} </td>
{% if perms.leaders.change_leader %}
            <td><a href="{% url 'leader_update' scout_ref.id %}"><button type="button" class="btn btn-primary">Update</button></a></td>
{% else %}
	    <td></td>
{% endif %}
    </tr>
    {% endfor %}
	    </tbody>
    </table>
{% endblock %}

django_troop/positions/templates/positions/positions_list.html
{% extends 'base.html' %}

{% block title %}Positions{% endblock %}

{% block content %}
    <table class="table table-striped table-hover">
	    <thead>
	    <tr>
            <th>Name</th>
            <th>Description</th>
{% if perms.positions.add_position %}
            <th><a href="{% url 'positions_create' %}"><button type="button" class="btn btn-success">Create New</button></a></th>
{% else %}
	    <th></th>
{% endif %}
	    </tr>
	    </thead>

	    <tbody>
	{% for position in positions %}
        <tr>
		<td><a href="{% url 'position_detail' position.id %}">{{ position.name }}</a></td>
		<td>{{ position.description }}</td>
{% if perms.positions.change_positions %}
		<td><a href="{% url 'positions_update' position.id %}"><button type="button" class="btn btn-primary">Edit</button></a></td>
{% else %}
		<td></td>
{% endif %}
        </tr>
        {% endfor %}
	    </tbody>
    </table>

{% endblock %}